### ISSUE TITLE
check_connection endpoint 404s

### ISSUE THREAD

**Issue by rxvl-d** [yasbil/yasbil#17]
I've encountered another obstacle. This time when I try to save the sync settings. It does not succeed with this error:

```
Unable to login to server using entered settings. Here is the error message:
Error: [E001] No response from server. Check server URL.
```

I have a wordpress installation running locally at `https://yasbil.test` (Wordpress works fine at that URL.) I've set up a test user and generated an application password. When I try to save the sync settings I see this: 

![Screenshot from 2023-07-05 13-47-40](https://github.com/LongSAL/yasbil/assets/81429688/e39c0b64-dac2-4e43-ade0-16c8d74db1f1)

As you can see, poking around in the devtools shows that the request is encountering a 404. Looking at the code, it seems like the right path. Any ideas about why it might be inaccessible?

**Comment by rxvl-d** [comment]
As a side note, discovered that this bit of code: https://github.com/LongSAL/yasbil/blob/main/yasbil-extn/yasbil_ui_options.js#L17-L19 prevents me from typing in the address because it deletes the `/` I type after `https:`. So, I have to copy paste `https://yasbil.test` in there. Not a big dea but could be another pain point for new users.

**Comment by nilavra** [comment]
@rxvl-d Thank you for pointing this out. When developing the extension, I was naively assuming that most users would copy-paste the entire URL from their browser window to the Server URL field; and therefore I wrote the script to auto delete any trailing slashes, as you encountered. If you have any suggestions on how to improve this, that would be wonderful!

**Comment by rxvl-d** [comment]
Thanks for the response @nilavra . Will think of solutions to that . Perhaps a different event.

Any idea what could be causing the 404 that's the main problem blocking me at the moment?

To be clear I did copy paste the url in and it still 404s. You can see in the devtools view that it seems to be hitting the right URL.

**Comment by nilavra** [comment]
Interesting. TBH I had always used it over a remote server and never really tested it on localhost / docker containers. Is it possible for you to test with a remote server? Or maybe see with PostMan or similar tools to check if the local URLs are getting resolved properly via your local DNS / hosts file?

Also, as a sidenote, the collected log data can be exported as a JSON file from the YASBIL browser extension itself. The WordPress connection exists to securely send the data to the server. The data recording can take place without that as well.

**Comment by rxvl-d** [comment]
Makes sense. No worries. I can debug this myself I think. I figured there should be a way to download the JSON file myself but I'm running into a problem with that as well. I assuming it's this button here?

![Screenshot from 2023-07-07 15-55-16](https://github.com/LongSAL/yasbil/assets/81429688/621e1ec8-4d4c-47b4-bebe-e49aa598a8f7)

When I click it nothing happens.

**Comment by rxvl-d** [comment]
I think I figured out why the local download doesn't work at a certain file size. It's because the `href` value here has a limit: https://github.com/LongSAL/yasbil/blob/c543643a8b05fce7299bfc91f6dac638ce7068cb/yasbil-extn/yasbil_ui_view_local_data.js#L50

Perhaps this: https://stackoverflow.com/questions/11849562/how-to-save-the-output-of-a-console-logobject-to-a-file is a more scalable solution. Use this function:

```
save = function(data, filename){

    if(!data) {
        console.error('Console.save: No data')
        return;
    }

    if(!filename) filename = 'console.json'

    if(typeof data === "object"){
        data = JSON.stringify(data, undefined, 4)
    }

    var blob = new Blob([data], {type: 'text/json'}),
        e    = document.createEvent('MouseEvents'),
        a    = document.createElement('a')

    a.download = filename
    a.href = window.URL.createObjectURL(blob)
    a.dataset.downloadurl =  ['text/json', a.download, a.href].join(':')
    e.initMouseEvent('click', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null)
    a.dispatchEvent(e)
 }
```

and call it with `save(json_export, json_filename)` there. I can make a PR for this if you're ok with this solution @nilavra. I've testing this in the console.
